export  const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST";
export  const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export  const GET_CUSTOMER_FAILURE = "GET_CUSTOMER_FAILURE";

export  const GET_CUSTOMER_PROFILE_REQUEST = "GET_CUSTOMER_PROFILE_REQUEST";
export  const GET_CUSTOMER_PROFILE_SUCCESS = "GET_CUSTOMER_PROFILE_SUCCESS";
export  const GET_CUSTOMER_PROFILE_FAILURE = "GET_CUSTOMER_PROFILE_FAILURE";